### ISSUE TITLE
Function Braking wordt later als Brake opgeroepen

### ISSUE THREAD

**Issue by DaanVanMullem** [HOGENT-Web/csharp#20]
1. Introduction to the .NET ecosystem; Slides; Slide nr 31/41
![image](https://user-images.githubusercontent.com/60927723/135064160-558f0ce8-ee63-43ee-b766-872038a18034.png)

**Comment by vertonghenb** [comment]
Fixed in #8c1af578ff0d1382fbb4591eb57fe6b6a06b012d
