### ISSUE TITLE
Typo Chapter 6, Slide 24 - Index.razor

### ISSUE THREAD

**Issue by jam53** [HOGENT-Web/csharp#41]
[**Chapter 6, Slide 24: Unboxing the Client - Index.razor**](https://hogent-web.github.io/csharp/chapters/06/slides/index.html#24)

On Slide 24, there's a code block that includes the line: `<PageTitle>Index</PageTitle>`. The explanation provided below the code block mentions:
> The name of the Page is called **Title** which is taken care of by the **PageTitle** component. This can be seen in the browser tab, since it manipules the **\<head\>** content of the **\<html\>**.

It appears that there might be an error in the explanation. I believe the name of the Page in this example should be "Index," rather than "Title." Therefore, the explanation below the code block should be corrected as follows:

> The name of the Page is called ~~**Title**~~ **Index** which is taken care of by the **PageTitle** component. This can be seen in the browser tab, since it manipules the **\<head\>** content of the **\<html\>**.

**Comment by vertonghenb** [comment]
@jam53 Correct, thanks!
